import axiosInstance from '@/shared/api/axiosInstance';

export interface Invoice {
  id: number;
  userId: number;
  amount: number;
  description: string;
  status: 'pending' | 'paid' | 'overdue' | 'cancelled';
  dueDate: string;
  paidAt: string | null;
  createdAt: string;
  isAutoGenerated: boolean;
  user?: {
    id: number;
    name: string;
    email: string;
    role: string;
  };
  creator?: {
    id: number;
    name: string;
    email: string;
  };
  payments?: Array<{
    id: number;
    amount: number;
    status: string;
    createdAt: string;
  }>;
}

export interface CreateInvoiceRequest {
  userId: number;
  amount: number;
  description: string;
  dueDate: string;
}

export interface InvoiceListResponse {
  success: boolean;
  data: {
    invoices: Invoice[];
    pagination: {
      page: number;
      limit: number;
      total: number;
      pages: number;
    };
  };
}

export interface InvoiceResponse {
  success: boolean;
  data: Invoice;
}

export interface PaymentResponse {
  success: boolean;
  data: {
    payment: {
      id: number;
      amount: number;
      status: string;
      createdAt: string;
    };
    invoice: {
      id: number;
      status: string;
      paidAt: string;
    };
    wallet: {
      balance: number;
    };
  };
}

class InvoiceService {
  // Получить счета пользователя
  static async getUserInvoices(params?: {
    page?: number;
    limit?: number;
    status?: string;
  }): Promise<InvoiceListResponse> {
    const response = await axiosInstance.get('/invoices/my', { params });
    return response.data;
  }

  // Получить все счета (админ)
  static async getAllInvoices(params?: {
    page?: number;
    limit?: number;
    status?: string;
    userId?: number;
  }): Promise<InvoiceListResponse> {
    const response = await axiosInstance.get('/invoices/all', { params });
    return response.data;
  }

  // Получить детали счета
  static async getInvoiceDetails(invoiceId: number): Promise<InvoiceResponse> {
    const response = await axiosInstance.get(`/invoices/${invoiceId}`);
    return response.data;
  }

  // Создать счет (админ)
  static async createInvoice(data: CreateInvoiceRequest): Promise<InvoiceResponse> {
    const response = await axiosInstance.post('/invoices', data);
    return response.data;
  }

  // Оплатить счет
  static async payInvoice(invoiceId: number): Promise<PaymentResponse> {
    const response = await axiosInstance.post(`/invoices/${invoiceId}/pay`);
    return response.data;
  }

  // Отменить счет (админ)
  static async cancelInvoice(invoiceId: number): Promise<InvoiceResponse> {
    const response = await axiosInstance.patch(`/invoices/${invoiceId}/cancel`);
    return response.data;
  }

  // Удалить счет (админ, только отмененные)
  static async deleteInvoice(invoiceId: number): Promise<{ success: boolean; message: string }> {
    const response = await axiosInstance.delete(`/invoices/${invoiceId}`);
    return response.data;
  }
}

export default InvoiceService;
