import { createAsyncThunk } from '@reduxjs/toolkit';
import InvoiceService, { CreateInvoiceRequest } from '../api/invoiceService';
import { setInvoices, setCurrentInvoice, setLoading, setError, setPagination, updateInvoice, removeInvoice } from './slice';

// Получить счета пользователя

export const fetchUserInvoices = createAsyncThunk(
  'invoice/fetchUserInvoices',
  async (params: { page?: number; limit?: number; status?: string } = {}, { dispatch }) => {
    try {
      dispatch(setLoading(true));
      const response = await InvoiceService.getUserInvoices(params);
      dispatch(setInvoices(response.data.invoices));
      dispatch(setPagination(response.data.pagination));
      return response.data;
    } catch (error: any) {
      dispatch(setError(error.response?.data?.message || 'Ошибка загрузки счетов'));
      throw error;
    } finally {
      dispatch(setLoading(false));
    }
  }
);

// Получить все счета (админ)
export const fetchAllInvoices = createAsyncThunk(
  'invoice/fetchAllInvoices',
  async (params: { page?: number; limit?: number; status?: string; userId?: number } = {}, { dispatch }) => {
    try {
      dispatch(setLoading(true));
      const response = await InvoiceService.getAllInvoices(params);
      dispatch(setInvoices(response.data.invoices));
      dispatch(setPagination(response.data.pagination));
      return response.data;
    } catch (error: any) {
      dispatch(setError(error.response?.data?.message || 'Ошибка загрузки счетов'));
      throw error;
    } finally {
      dispatch(setLoading(false));
    }
  }
);

// Получить детали счета
export const fetchInvoiceDetails = createAsyncThunk(
  'invoice/fetchInvoiceDetails',
  async (invoiceId: number, { dispatch }) => {
    try {
      dispatch(setLoading(true));
      const response = await InvoiceService.getInvoiceDetails(invoiceId);
      dispatch(setCurrentInvoice(response.data));
      return response.data;
    } catch (error: any) {
      dispatch(setError(error.response?.data?.message || 'Ошибка загрузки счета'));
      throw error;
    } finally {
      dispatch(setLoading(false));
    }
  }
);

// Создать счет (админ)
export const createInvoice = createAsyncThunk(
  'invoice/createInvoice',
  async (data: CreateInvoiceRequest, { dispatch }) => {
    try {
      dispatch(setLoading(true));
      const response = await InvoiceService.createInvoice(data);
      dispatch(setCurrentInvoice(response.data));
      return response.data;
    } catch (error: any) {
      dispatch(setError(error.response?.data?.message || 'Ошибка создания счета'));
      throw error;
    } finally {
      dispatch(setLoading(false));
    }
  }
);

// Оплатить счет
export const payInvoice = createAsyncThunk(
  'invoice/payInvoice',
  async (invoiceId: number, { dispatch }) => {
    try {
      dispatch(setLoading(true));
      const response = await InvoiceService.payInvoice(invoiceId);
      
      // Обновляем счет в списке - используем только ID для поиска существующего счета
      dispatch(updateInvoice({
        id: response.data.invoice.id,
        userId: 0,
        amount: 0,
        description: '',
        dueDate: '',
        status: 'paid' as const,
        paidAt: response.data.invoice.paidAt,
        createdAt: '',
        isAutoGenerated: false,
      }));
      
      return response.data;
    } catch (error: any) {
      dispatch(setError(error.response?.data?.message || 'Ошибка оплаты счета'));
      throw error;
    } finally {
      dispatch(setLoading(false));
    }
  }
);

// Отменить счет (админ)
export const cancelInvoice = createAsyncThunk(
  'invoice/cancelInvoice',
  async (invoiceId: number, { dispatch }) => {
    try {
      dispatch(setLoading(true));
      const response = await InvoiceService.cancelInvoice(invoiceId);
      dispatch(updateInvoice(response.data));
      return response.data;
    } catch (error: any) {
      dispatch(setError(error.response?.data?.message || 'Ошибка отмены счета'));
      throw error;
    } finally {
      dispatch(setLoading(false));
    }
  }
);

// Удалить счет (админ, только отмененные)
export const deleteInvoice = createAsyncThunk(
  'invoice/deleteInvoice',
  async (invoiceId: number, { dispatch }) => {
    try {
      dispatch(setLoading(true));
      await InvoiceService.deleteInvoice(invoiceId);
      dispatch(removeInvoice(invoiceId));
      return invoiceId;
    } catch (error: any) {
      dispatch(setError(error.response?.data?.message || 'Ошибка удаления счета'));
      throw error;
    } finally {
      dispatch(setLoading(false));
    }
  }
);

